language: java
jdk:
 - oraclejdk11
script:
  - ./mvnw test
cache:
  directories:
    - '$HOME/.m2/repository'
deploy:
 provider: heroku
 api-key:
  secure: 'ab795dd7-b09a-4157-a6c6-a2b3f1f7ed89'
 app: projet-catho-back
